# internal CA
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ca-self-issuer
  namespace: cert-manager
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: internal-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: internal-ca
  subject:
    organizations:
      - Giga Breslau SA
    organizationalUnits:
      - Super Department
  dnsNames:
    - internal-ca.localtest.me
    - '*.localtest.me'
  secretName: internal-ca-keypair
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: ca-self-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: internal-ca
spec:
  ca:
    secretName: internal-ca-keypair
