# generator certyfikatów zaufanych; ale domena i serwer muszą być publiczne
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-nginx
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ${EMAIL}
    privateKeySecretRef:
      name: letsencrypt-cert
    solvers:
    - http01:
        ingress:
          class: nginx