apiVersion: apps/v1
kind: Deployment
metadata:
 name: hello-app
spec:
 replicas: 1
 selector:
   matchLabels:
     app: hello
 template:
   metadata:
     labels:
       app: hello
   spec:
     containers:
     - name: hello
       image: gcr.io/google-samples/hello-app:1.0
       ports:
       - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
 name: hello-service
spec:
 selector:
   app: hello
 ports:
 - port: 80
   targetPort: 8080
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: today-ingress
spec:
  secretName: today-ingress
  isCA: false
  commonName: hello
  subject:
    organizations:
      - Giga Breslau SA
    organizationalUnits:
      - Hello Department
  dnsNames:
  - hello.localtest.me
  - hello
  issuerRef:
    name: internal-ca
    kind: ClusterIssuer
  usages:
    - client auth
    - server auth
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: today-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/issuer: internal-ca
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - hello.localtest.me
      # not must to be here
      #secretName: today-ingress
  rules:
    - host: hello.localtest.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-service
                port:
                  number: 80
